### ISSUE TITLE
Нет зеленой кнопки автотеста.Сделал все по гайду не помогает

### ISSUE THREAD

**Issue by TemPoun** [Kseen715/Kseen715#1]
Нет зеленой кнопки автотеста.Сделал все по гайду не помогает,помоги бро по поводу Автотеста НМО

**Comment by Kseen715** [comment]
Сверь адрес в шапке скрипта и какой у тебя сайт. Если отличается, там еще в некоторых местах его поменять надо. А так - пиши автору, он активен. Я тут вообще мимо проходил

**Comment by TemPoun** [comment]
Автор не отвечает,помоги пожалуйста,я буду благодарен

**Comment by TemPoun** [comment]
Мне срочно нужно прошу
