### ISSUE TITLE
Пожалуйста помоги

### ISSUE THREAD

**Issue by TemPoun** [Kseen715/Kseen715#2]
Помоги,автор не отвечает,есть его контанкты,мне срочно нужно эти автотесты НМО.

**Comment by Kseen715** [comment]
Я не знаю в чем твоя проблема. Я не автор и знать все не могу. С автором я вообще никак не связан. Если мой прошлый совет тебе не помог - открывай консоль и читай логи и код, в коде буквально каждая строчка подписана.

P.S. Не спамь в issues не по теме, это наказуемо
